### ISSUE TITLE
3D scene issue - no effect is seen

### ISSUE THREAD

**Issue by SupMike** [paulloz/godot-colorblindness#2]
I hope that's not just me (and that I'm doing something stupidly, embarassingly wrong), but I'm having trouble with the addon in a 3d scene.

I created a gradient material and applied it to a plane to test the functionality, but here's my repro:

1. Create a 3D scene
2. Add a camera
3. Add a meshinstance
4. Create a Plane
5. Create a material that would easily show a difference in color perception (I created a simple gradient on albedo)
6. Follow the steps found in usage: add a CanvasLayer
7. Add Colorblindness.gd as a child
8. Change the colorblindness type from the Type dropdown
9. Save and run scene.
10. Notice no change in color.

![2020-05-11 15_24_22-jumpcut](https://user-images.githubusercontent.com/20129156/81566835-b985f780-939b-11ea-9ca6-ea9191cd6837.png)

**Comment by paulloz** [comment]
Hey, thanks for the report.  
This is a timing bug: the material isn't properly loaded yet when I'm setting the shader parameters. I'm working on a fix right now.

**Comment by paulloz** [comment]
This should be fixed as of [v1.3](https://github.com/paulloz/godot-colorblindness/releases/tag/v1.3), please let me know. I tested with Godot's 3D platformer demo.  
Update is awaiting approval on the assets library.

**Comment by SupMike** [comment]
Great! I just tested it on my side and it works as intended now. Great work, thanks a bunch. AFAIK the bug is fixed.

**Comment by paulloz** [comment]
Always happy to see people using this addon 😁
