### ISSUE TITLE
Mouse input bug

### ISSUE THREAD

**Issue by byjtew** [paulloz/godot-colorblindness#3]
If you place the Colorblind canvas as a parent or even root of your scene, you may not be able to use any screen input.
To fix this you need to add the IGNORE property to the inner Colorblind's ColorRect node like this:
``` GDSCRIPT
func _ready():
	self.add_child(self.rect)

	self.rect.rect_min_size = self.rect.get_viewport_rect().size
	self.rect.material = load("res://addons/paulloz.colorblindness/colorblindness.material")
	self.rect.set_mouse_filter(2) # ADD THIS LINE
	if self.temp:
		self.Type = self.temp
		self.temp = null

	self.get_tree().root.connect('size_changed', self, '_on_viewport_size_changed')
```

**Comment by paulloz** [comment]
👌 This is an oversight from my part. It's done on master (96e2576) and will be packaged in the next release.  
Thanks for the report.
