### ISSUE TITLE
Black screen on GLES2

### ISSUE THREAD

**Issue by cmrqs** [paulloz/godot-colorblindness#4]
Hello! I'm not sure if this is GLES3-only, but I get the following error using GLES2:

`E 0:00:00.436   _copy_screen: Can't use screen texture copying in a render target configured without copy buffers.
  <C++ Error>   Condition "storage->frame.current_rt->copy_screen_effect.color == 0" is true.
  <C++ Source>  drivers/gles2/rasterizer_canvas_base_gles2.cpp:734 @ _copy_screen()`

**Comment by paulloz** [comment]
I just tried with a brand new GLES2 project and didn't experience any issue. Could you share your environment details?
* Godot version
* OS version
* GPU model + driver version

Thanks!

**Comment by cmrqs** [comment]
Thanks for the quick response!

- **Godot version:** Custom build 3.3.4 (also tested on 3.3.3-stable, same issue)
- **OS version:** Coding in Arch Linux, exporting to Android 10 (also same issue)
-  **GPU model + driver version:** GeForce GTX 1650 (nvidia-dkms 470.74) | Adreno 630 OpenGL 3.2

As you can see in [this image](https://i.imgur.com/rqNQnmp.png), it does work on editor, but I get [this](https://i.imgur.com/dcfx3Ze.png) (both on Linux and Android) when executed.

**Comment by cmrqs** [comment]
Oh! So I found what's wrong. I had "Framebuffer Allocation" set as "2D without Sampling". When I changed to "2D" it worked :)

Maybe you should add this to README?
